[package]
name = "rustsp"
version = "0.2.0"
edition = "2021"

[lib]
name = "rustsp"
path = "src/lib.rs"

[[bin]]
name = "rustsp"
path = "src/main.rs"

[[bin]]
name = "cargo-rustsp"
path = "src/bin/cargo-rustsp.rs"

[dependencies]